version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'

    default_reviewers:
      - 'julianosbento'
      - 'victorheringer'
      - 'murillo94'
      - 'pleaobraga'
      - 'an-mag'
      - 'LopesAlysson'
      - 'pedro-cerdera'
      - 'caiogodoi'
      - 'carlosberti'
    default_assignees:
      - 'julianosbento'
      - 'victorheringer'
      - 'murillo94'
      - 'pleaobraga'
      - 'an-mag'
      - 'LopesAlysson'
      - 'pedro-cerdera'
      - 'caiogodoi'
      - 'carlosberti'
