export { default as CallIcon } from './Call';
export { default as EmailIcon } from './Email';
export { default as EmailAdressIcon } from './EmailAdress';
export { default as EmailOpenIcon } from './EmailOpen';
export { default as EmailSendIcon } from './EmailSend';
export { default as MessageIcon } from './Message';
export { default as MessageAltIcon } from './MessageAlt';
export { default as MessageQuestionIcon } from './MessageQuestion';
export { default as SupportIcon } from './Lifebuoy';
